# Generated by Django 6.0 on 2026-01-07 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, choices=[('1', '1st Year'), ('2', '2nd Year'), (
                    '3', '3rd Year'), ('4', '4th Year'), ('G', 'Graduate')], max_length=1)),
                ('majors_minors', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, choices=[
                 ('M', 'Male'), ('F', 'Female'), ('O', 'Other / Prefer Not to Say')], max_length=1, null=True)),
                ('preferred_meeting_times', models.CharField(
                    blank=True, max_length=100)),
                ('preferred_meeting_location', models.CharField(
                    blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
